name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main  # Trigger when main branch gets a push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the GitHub Contributions Snake Animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: Vortex-16
          outputs: |
            dist/github-snake.svg?color_snake=#FF073A
            dist/github-snake-dark.svg?color_snake=#FF073A
            dist/ocean.gif?color_snake=#FF073A
        env:
          home: ${{ secrets.PERSONAL_TOKEN }}

      # Step 3: Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update colorful snake animations [skip ci]"
