name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: Vortex-16
          outputs: |
            dist/github-snake.svg?color_snake=#FF073A
            dist/github-snake-dark.svg?color_snake=#FF073A

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # OR use PERSONAL_TOKEN
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animations [skip ci]"
